### ISSUE TITLE
error in extracting scaffolds and essential genes

### ISSUE THREAD

**Issue by ankit4035** [MadsAlbertsen/multi-metagenome#10]
At above mentioned step by using the command:
g1.e.A <- extract(es, g1.selection.A, es[, x], es[, y])

g1.e.A file is not generated as it has NULL values.

Hence further steps are also not working as expected.
On calculating stats using calc.genome.stats function following error is encountered:
Error in matrix(c(sum(x$length), nrow(x), round(mean(x$length), 1), max(x$length),  : 
  length of 'dimnames' [1] not equal to array extent

I am using the dataset provided by you and encountering above problems. Please help me out..

**Comment by MadsAlbertsen** [comment]
Hi,

The error was introduced after the alphahull package was updated (not by us). See [here](https://github.com/MadsAlbertsen/multi-metagenome/issues/6) for a fix.

Alternatively you could try our new package [mmgenome](http://madsalbertsen.github.io/mmgenome/) which makes everything much more easy...

Let me know if it fixed your problem.

rgds
Mads

**Comment by ankit4035** [comment]
Hello,

It did solve my problem. Thanks for your quick response. :-)

Regards,
Ankit
