### ISSUE TITLE
Error while extracting Verrumicrobia genome in demo data

### ISSUE THREAD

**Issue by dbrami** [MadsAlbertsen/multi-metagenome#13]
Hi,
Thank you for making the tool that I needed and wanted to make!!
I'm going through the the demo and I'm getting stuck.
Here's the result I get:

``` R
    >calc.genome.stats(g1.s.A, g1.e.A)
    Error in matrix(c(sum(x$length), nrow(x), round(mean(x$length), 1), max(x$length),  : 
    length of 'dimnames' [1] not equal to array extent
```

The command:

``` R
g1.e.A<-extract(es,g1.selection.A,es[,x],es[,y])
```

yields no errors but creates a NULL variable.

Any ideas?

**Comment by MadsAlbertsen** [comment]
Hi, 

I would highly recommend to take a look at our [mmgenome package](http://madsalbertsen.github.io/mmgenome/) instead. It wraps everything in easy to use R functions instead.

**Comment by dbrami** [comment]
Thank you Mads.
