### ISSUE TITLE
Hi, Mads, I love mmsubset, but there's a small problem with it

### ISSUE THREAD

**Issue by nmb85** [MadsAlbertsen/multi-metagenome#14]
The essential gene dataframe gets subset incorrectly, I think.

This:
e_new <- subset(data$essential, d_new$scaffold %in% data$essential$scaffold)

Should be this:
e_new <- subset(data$essential, data$essential$scaffold %in% d_new$scaffold)

My original, reproducible problem (load the data and then run the R script):
https://www.dropbox.com/sh/9437fece57li47u/AABNZuC44tJleLEBKQhrnhmKa?dl=0

**Comment by MadsAlbertsen** [comment]
Thanks for spotting it. It should be fixed now (in the mmgenome package v.0.6.1).
