### ISSUE TITLE
What is the formate of 'list.of.scaffols.txt -o'?

### ISSUE THREAD

**Issue by LouieF** [MadsAlbertsen/multi-metagenome#17]
Hello~
I am reading the 'Metagenome Assembly Guide'. However I can't understand what is the format of 

'list.of.scaffols.txt -o' in step 11: reassembly. Should I just retrieve the heads of my scaffolds.fa file and 

write each head in one line of a .txt file?

Can you specify it, many thanks!
Yifan

**Comment by MadsAlbertsen** [comment]
It should simply be the name of each scaffold: 1 scaffold pr. line in a plain text file.

However, I would highly suggest to use our new [mmgenome](http://madsalbertsen.github.io/mmgenome/) workflow instead. It is much more easy to use and have many additional features.

**Comment by LouieF** [comment]
I tried it, but it didn't work. I may need to read mmgenome instead.
Thanks a lot!

**Comment by MadsAlbertsen** [comment]
Please do use mmgenome instead. Its much better and more easy to use.
