### ISSUE TITLE
blastp trouble

### ISSUE THREAD

**Issue by adoloman** [MadsAlbertsen/multi-metagenome#4]
While running blastp command, for finding essential genes - Blasting positive hits, an error occurs:

BLAST Database error: No alias or index file found for protein database [refseq_protein] in search path [~/software/multi-metagenome/R.data.generation::]

I assumed that blastp is done through server connection, so it doesn't need any databases, such as refseq_protein to be present on a local computer. If it is so, why does this error occur?

**Comment by MadsAlbertsen** [comment]
It is done locally. Hence, you need to download the refseq_protein database (or any other database you prefer).

**Comment by adoloman** [comment]
Still. I downloaded refseq_protein database and specified a path to it, but the error occurs again. I cannot understand why it's looking for an index in the ZR.data.generation folder, if I specified where the database is:

> > blastp -query IIa.orfs.hmm.faa -db .../db/refseq_protein -evalue 1e-5 -num_threads 60 -max_target_seqs 5 -outfmt 5 -out IIa.orfs.hmm.blast.xml

And the error is:

> > BLAST Database error: No alias or index file found for protein database [.../db/refseq_protein] in search path [.../software/multi-metagenome/R.data.generation::]

**Comment by MadsAlbertsen** [comment]
How did you make the blast database? You probably need to make it using the makeblastdb tool (see http://www.ncbi.nlm.nih.gov/books/NBK1763/).

If you have made the database - then try to use the absolute file path.

**Comment by adoloman** [comment]
Yes, I used command makeblastdb, and specified the absolute path. It doesn't work.

> > Command line argument error: Argument "query". File is not accessible:  `~/software/multi-metagenome/R.data.generation/IIa.orfs.hmm.faa.db'

**Comment by MadsAlbertsen** [comment]
Could you send the complete command you entered? 

Have you been able to blast any other dataset from the command line?

**Comment by adoloman** [comment]
Sure.
For database it was:

> > makeblastdb -in IIa.orfs.hmm.faa -dbtype nucl -out IIa.orfs.hmm.faa.db
> > And for the actual blast:
> > blastp -query /home/bwawrik/software/multi-metagenome/R.data.generation/IIa.orfs.hmm.faa.db -db /home/bwawrik/db/refseq_protein -evalue 1e-5 -num_threads 60 -max_target_seqs 5 -outfmt 5 -out IIa.orfs.hmm.blast.xml

I have done blast from the command line on different local computer, not from this particular one.

**Comment by MadsAlbertsen** [comment]
You need to run makeblastdb on you refseq_protein file:

makeblastdb -in refseq_protein -dbtype prot

blastp -query IIa.orfs.hmm.faa -db refseq_protein -evalue 1e-5 -num_threads 60 -max_target_seqs 5 -outfmt 5 -out IIa.orfs.hmm.blast.xml

**Comment by adoloman** [comment]
Ok, but how can I unite all the files from refseq_protein in one command to perform mekeblastdb command?? there are those different  .pni .pnd .pog files and all of them are related to 00-09 types of refseq_protein.

**Comment by adoloman** [comment]
Yeah, I specified asterics *, and it seems to understand me... but,  another error:

> > makeblastdb -in /home/bwawrik/db/refseq_protein.\* -dbtype prot -out /home/bwawrik/db/refseq_protein.db
> > USAGE
> >   makeblastdb [-h] [-help] [-in input_file] [-input_type type]
> >     -dbtype molecule_type [-title database_title] [-parse_seqids]
> >     [-hash_index] [-mask_data mask_data_files] [-gi_mask]
> >     [-gi_mask_name gi_based_mask_names] [-out database_name]
> >     [-max_file_sz number_of_bytes] [-taxid TaxID] [-taxid_map TaxIDMapFile]
> >     [-logfile File_Name] [-version]

DESCRIPTION
   Application to create BLAST databases, version 2.2.28+

# Use '-help' to print detailed descriptions of command line arguments

Error: Too many positional arguments (1), the offending value: /home/bwawrik/db/refseq_protein.01.phr

**Comment by MadsAlbertsen** [comment]
It seems like you've already downloaded the database formatted version of refseq_protein. You will probably need to use the blastdb_aliastool to make a single reference for the formatted database.

**Comment by adoloman** [comment]
Blastdb_aliastool doesn't work as well, giving an error:

> > Too many positional arguments (1), the offending value:  -out
> > seems like it is impossible to unite such a big amount of database files.
> > Could you please tell me, what exactly refseq_protein you were using in your research?

**Comment by MadsAlbertsen** [comment]
I was just using the latest official refseq_protein database from NCBI. This is how I normally update the blast databases on our server using the NCBI script [update_blastdb.pl](http://www.ncbi.nlm.nih.gov/blast/docs/update_blastdb.pl)

Download the databases from NCBI:

```
update_blastdb.pl refseq_protein
```

Extract all downloaded files:

```
for i in refseq_protein*.tar.gz; do tar xzvf $i; done
```

Combine the database into one file using `blastdb_aliastool`: 

```
blastdb_aliastool -dblist "refseq_protein.01 refseq_protein.02 refseq_protein.03 refseq_protein.04 refseq_protein.05 refseq_protein.06" -title refseq_protein -out refseq_protein -dbtype prot
```

Check the version of the database:

```
blastdbcmd -info -db refseq_protein
```

**Comment by adoloman** [comment]
Oh, that's right. Thank you so much!
I actually finally managed to run it without combining databases in to one file.

**Comment by emmannaemeka** [comment]
Hello, Can someone help. I am trying to do run NCBI on local computer and i keep getting this error

emmannaemekas-MacBook-Pro:~ emmannaemeka$ blastp -query muc1_genome_snap2.all.maker.snap_masked.proteins.fasta -db swissprot -out muc2.fa
Command line argument error: Argument "query". File is not accessible:  `muc1_genome_snap2.all.maker.snap_masked.proteins.fasta'

what do I do?

**Comment by adoloman** [comment]
Hi,
Where is your fasta file located? Since you run the blastp command from home directory, you should either re-locate fasta file to the home directory or provide full path to it in the command (smth like: home/user/FolderName/*.fasta)
