### ISSUE TITLE
MEGAN no results

### ISSUE THREAD

**Issue by achauha1** [MadsAlbertsen/multi-metagenome#7]
Hi,
 I am a newbie to metagenomics. I assembly my sequences using clc and performed all he steps till MEGAN. After running magan, i am getting following "oneline" output 

"NODE_203150_length_160_cov_3.043750_1   root;cellular organisms;Bacteria"

I am not sure what is wrong. 

I would appreciate if you could help me. Thanks
Arc

**Comment by MadsAlbertsen** [comment]
Hi Arc,

I'll  need to know more about the dataset to help.

First of all the header of the scaffold "NODE_203150...." indicate that you assembled the sequences with velvet and not clc? Velvet is not suited for metagenome assembly.

What was the statistics of your de novo assembly? E.g. in terms of total size, number of scaffolds, mean length, the number of input reads etc?

If it's an extremely poor assembly it might be that you only get 1 classified scaffold.

rgds
Mads

**Comment by achauha1** [comment]
Hi Mads,

Thanks you so much for you response. I realized that i used a wrong
assembly file for my analyses.

I am still getting error while running the program.

this time the error is "

> ggplot(ds, aes(x = Assembly1, y = Assembly2, color = gc, size = length)) Error: No layers in plot

I am not sure why it's not working.

To give you an insight into my project here's a little detail:

1) I made different illumina libraries (from two different depth) from
the same sampling site.

2) we sequenced it on Hiseq 2000 as 2x 100 bp run.

3) Raw reads were trimmed using CLC workbench and assembled (with
scaffolding option) and mapping the reads back to the contigs. This
provided the coverage information. The kmer used was 57.

4) The two assemblies were merged  for use of your pipeline.

Attached please find my assembly stats and all other files that i used
for R-studio. Any help is greatly appreciated. Thank you.

Best regards,

Arc​
 65assembly_summary_report.pdf
https://docs.google.com/file/d/0B49BmzHVy1DkZmFSWnBaanBuaEU/edit?usp=drive_web
​​
 65cm_assembly.csv
https://docs.google.com/file/d/0B49BmzHVy1DkbmxvNmpDMzFmUUU/edit?usp=drive_web
​​
 65cm_assembly.xls
https://docs.google.com/file/d/0B49BmzHVy1DkVWN6SC1VSkg0UGs/edit?usp=drive_web
​​
 assembly.fa https://docs.google.com/file/d/0B49BmzHVy1DkU2ZUN2hrbjB2cDA/edit?usp=drive_web
​​
 assembly.gc.tab
https://docs.google.com/file/d/0B49BmzHVy1DkZmM2RzY0bS1CWjQ/edit?usp=drive_web
​​
 assembly.hmm.orfs.txt
https://docs.google.com/file/d/0B49BmzHVy1DkS25oVlRxMkdVQ3c/edit?usp=drive_web
​​
 assembly.kmer.tab
https://docs.google.com/file/d/0B49BmzHVy1DkNmFSOWtBOHZqUjA/edit?usp=drive_web
​​
 assembly.orfs.faa
https://docs.google.com/file/d/0B49BmzHVy1DkLTJiVndQUFMyX0k/edit?usp=drive_web
​​
 assembly.orfs.hmm.blast.tax.tab
https://docs.google.com/file/d/0B49BmzHVy1DkY0VWSkw4SlZNR0k/edit?usp=drive_web
​​
 assembly.orfs.hmm.blast.tax.txt
https://docs.google.com/file/d/0B49BmzHVy1DkU0I1ZUsyMDBxZjQ/edit?usp=drive_web
​​
 assembly.orfs.hmm.blast.xml
https://docs.google.com/file/d/0B49BmzHVy1DkZkUzVlFKSlk5RG8/edit?usp=drive_web
​​
 assembly.orfs.hmm.faa
https://docs.google.com/file/d/0B49BmzHVy1DkNnNjU21hQ0Q2Rnc/edit?usp=drive_web
​​
 assembly.orfs.hmm.id.txt
https://docs.google.com/file/d/0B49BmzHVy1DkbllzdEIyb3pvdTQ/edit?usp=drive_web
​​
 assembly.tax.consensus.txt
https://docs.google.com/file/d/0B49BmzHVy1DkYkY5YURTdmtkZnc/edit?usp=drive_web
​​
 hmm.temp.txt https://docs.google.com/file/d/0B49BmzHVy1DkNVZhT2x6d0tnYkk/edit?usp=drive_web
​​
 list.of.positive.orfs.txt
https://docs.google.com/file/d/0B49BmzHVy1DkX2F5NW1SNGs5QUk/edit?usp=drive_web
​​
 metagenome.workflow.R
https://docs.google.com/file/d/0B49BmzHVy1DkVFZGR2YwcVZ0dFU/edit?usp=drive_web
​​
 PF_assembly.csv
https://docs.google.com/file/d/0B49BmzHVy1DkRzY3NUFTZlB2Smc/edit?usp=drive_web
​​
 PF_assembly.xls
https://docs.google.com/file/d/0B49BmzHVy1DkYTk1eG1MbWJTZUU/edit?usp=drive_web
​​
 PFassembly_summary_report.pdf
https://docs.google.com/file/d/0B49BmzHVy1Dkc1ZwLTR4cGdGX3M/edit?usp=drive_web
​

On Mon, Apr 7, 2014 at 1:25 PM, Mads Albertsen notifications@github.comwrote:

> Hi Arc,
> 
> I'll need to know more about the dataset to help.
> 
> First of all the header of the scaffold "NODE_203150...." indicate that
> you assembled the sequences with velvet and not clc?
> 
> What was the statistics of your de novo assembly? E.g. in terms of total
> size, number of scaffolds, mean length, the number of input reads etc?
> 
> If it's an extremely poor assembly it might be that you only get 1
> classified scaffold.
> 
> rgds
> Mads
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MadsAlbertsen/multi-metagenome/issues/7#issuecomment-39758345
> .

## 

archie

**Comment by MadsAlbertsen** [comment]
Hi Arc,

You need to add something like 
"+ geom_point()" 

see: http://madsalbertsen.github.io/multi-metagenome/docs/step9.html

**Comment by achauha1** [comment]
Hi Mads,
Thank you for your response.

I got it working  and was able to get the first plot "Coverage plot -
Colored by GC"

BUT

the second plot "Coverage plot - Colored by phylum level assignment of
essential genes" is all black colored. I cannot differentiate between
phyla and do not get figure legends (for phyla). I am not sure where i am
making mistakes. I am using exactly same parameters as published in your
website (to make sure that it working on my data).

Attached please find the plots for your reference.

Thank you.

Best regards,
Arc

On Fri, May 16, 2014 at 2:10 AM, Mads Albertsen notifications@github.comwrote:

> Hi Arc,
> 
> You need to add something like
> "+ geom_point()"
> 
> see: http://madsalbertsen.github.io/multi-metagenome/docs/step9.html
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MadsAlbertsen/multi-metagenome/issues/7#issuecomment-43300306
> .

## 

archie

**Comment by achauha1** [comment]
Hi Mads,
Thank you for your response.

I got it working  and was able to get the first plot "Coverage plot -
Colored by GC"

BUT

the second plot "Coverage plot - Colored by phylum level assignment of
essential genes" is all black colored. I cannot differentiate between
phyla and do not get figure legends (for phyla). I am not sure where i am
making mistakes. I am using exactly same parameters as published in your
website (to make sure that it working on my data).

Attached please find the plots for your reference.

Thank you.

Best regards,
Arc
