### ISSUE TITLE
Error: could not find function "clean_tax"

### ISSUE THREAD

**Issue by msalvacion** [MadsAlbertsen/multi-metagenome#8]
Hi Mads,

I'm attempting to run your Genome Extraction workflow, but I'm currently experiencing the following error in the Load_data.R script. In which package can i locate the clean_tax function? The output from sessionInfo() is as follows:

> sessionInfo()
> R version 3.1.1 (2014-07-10)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> 
> locale:
> [1] LC_COLLATE=English_United States.1252 
> [2] LC_CTYPE=English_United States.1252  
> [3] LC_MONETARY=English_United States.1252
> [4] LC_NUMERIC=C  
> [5] LC_TIME=English_United States.1252    
> 
> attached base packages:
> [1] parallel  grid      stats     graphics  grDevices utils     datasets 
> [8] methods   base     
> 
> other attached packages:
>  [1] mmgenome_0.2.1      plyr_1.8.1          reshape2_1.4  
>  [4] igraph_0.7.1        Biostrings_2.32.1   XVector_0.4.0  
>  [7] IRanges_1.22.9      BiocGenerics_0.10.0 vegan_2.0-10  
> [10] lattice_0.20-29     permute_0.8-3       knitr_1.6  
> [13] ggplot2_1.0.0       gridExtra_0.9.1     sp_1.0-15  
> [16] devtools_1.5       
> 
> loaded via a namespace (and not attached):
>  [1] colorspace_1.2-4 digest_0.6.4     evaluate_0.5.5   formatR_0.10  
>  [5] gtable_0.1.2     httr_0.3         MASS_7.3-33      memoise_0.2.1  
>  [9] munsell_0.4.2    proto_0.3-10     Rcpp_0.11.2      RCurl_1.95-4.1  
> [13] scales_0.2.4     stats4_3.1.1     stringr_0.6.2    tools_3.1.1  
> [17] whisker_0.3-2    zlibbioc_1.10.0 

Thank you for your time.

Michael

**Comment by MadsAlbertsen** [comment]
Hi Michael,

I can see that you are using the mmgenome R package and not the workflow described in this github repository. The mmgenome package is currently under development and the branch available on github is not working at the moment. I expect to put up a working version within the next couple of days.

rgds
Mads
