### ISSUE TITLE
re-assembly with alternate binning method

### ISSUE THREAD

**Issue by lebetimonas** [MadsAlbertsen/multi-metagenome#9]
I would like to use your extract.fasta.from.list.pl script using a .sam mapping file and a list of scaffolds of interest from ESOM binning. Can you show me an example of what your list file looks like? If I run the script with my sam file and a simple text file listing the scaffolds I want, I don't get an errors, just an empty output fasta file. Thanks for your help!

**Comment by MadsAlbertsen** [comment]
Are you using the right script: "extract.fasta.from.sam.using.list.pl" from the reassembly folder?

Make sure the scaffold names are the same as listed in the SAM file. Then it "should" work. Otherwise try sending a small example of your files.

**Comment by lebetimonas** [comment]
Yes, I am using the script extract.fasta.from.sam.using.list.pl (I see I put the wrong name the first time). 

The beginning of my sam file looks like this:
@HD     VN:1.0  SO:unsorted
@SQ     SN:scaffold_140 LN:130922
@SQ     SN:scaffold_184 LN:80650
@SQ     SN:scaffold_192 LN:74662
@SQ     SN:scaffold_193 LN:74043
@SQ     SN:scaffold_209 LN:128580
@SQ     SN:scaffold_218 LN:146729
@SQ     SN:scaffold_228 LN:66027

And the beginning of my list of scaffolds looks like this:
scaffold_140
scaffold_184
scaffold_192
scaffold_193
scaffold_209
scaffold_218
scaffold_228

I do not have a header on the list of scaffolds (is this the problem?) and in this case, I have mapped my reads to a fasta file containing only the scaffolds in the bin I am interested in. The goal is to use this fasta with the binned scaffolds and a fasta of reads mapping (or partially mapping) to these scaffolds to use for a new genome assembly. Thank you for your help.

**Comment by MadsAlbertsen** [comment]
Hmm. It looks fine. Can you send me a small example dataset that recreates the problem? Then I can figure out what is going wrong (MadsAlbertsen85@gmail.com).

**Comment by AnaSui** [comment]
I'm having this problem too, are there any solutions?
